Add `/rebase` command
pulumi/pulumi pull request #11028
Opened 2022-10-14 18:58 UTC by aq17

# Description

Fixes #10904

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

2022-10-14 18:59 UTC, aq17 commented
`/rebase` to rebase, `/autosquash` or `rebase-autosquash` to autosquash 
https://github.com/cirrus-actions/rebase

2022-10-17 22:16 UTC, AaronFriel requested changes
No issue with this PR, but we might want to expand on it or make an upstream PR to cirrus-actions to support a true "/squash" mode, that squashes all commits.

I think after restricting access, we can merge this and I can revisit #10904 this week

2022-10-17 22:16 UTC, AaronFriel commented on .github/workflows/rebase.yml
> +        contains(github.event.comment.body, '/autosquash')
I think this won't quite implement #10904, `autosquash` performs `git rebase --autosquash`, which doesn't squash _all_ commits.

2022-10-17 22:16 UTC, AaronFriel commented on .github/workflows/rebase.yml
> +      github.event.issue.pull_request != '' &&
I think we'll want to restrict this here to collaborators (people who have push access) https://github.com/cirrus-actions/rebase#restricting-who-can-call-the-action

I believe the permission we want is "COLLABORATOR" not "MEMBER"

2022-10-18 18:32 UTC, AaronFriel approved these changes
LGTM!

2022-10-18 18:37 UTC, aq17 commented
bors merge

2022-10-18 19:54 UTC, merged