Add standardized program-gen reporting helpers
pulumi/pulumi pull request #11032
Opened 2022-10-14 20:46 UTC by iwahbe

Initial  Report

# Description

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

2022-10-14 23:18 UTC, aq17 approved these changes

2022-10-17 22:06 UTC, AaronFriel commented on pkg/codegen/report/report.go
> +func (r *reporter) Report(title, language string, files []*syntax.File, f GenerateProgramFn) GenerateProgramFn {
Include a unit test of the output?

2022-10-17 22:07 UTC, AaronFriel requested changes
Would make sense to add a test, even if just to show an example of how to use the reporter

2022-10-18 17:55 UTC, iwahbe commented
> Would make sense to add a test, even if just to show an example of how to use the reporter

Examples have been added.

2022-10-18 18:32 UTC, AaronFriel approved these changes

2022-10-18 22:35 UTC, iwahbe commented
bors r+

2022-10-18 23:05 UTC, merged