update some names for registry
pulumi/pulumi pull request #11506
Opened 2022-12-01 18:38 UTC by susanev

fixing up some names for regsitry for seo and usability reasons

2022-12-01 18:40 UTC, susanev commented on pkg/codegen/docs/gen.go
> +		"artifactory":				"Artifactory",
```suggestion
		"artifactory":                             "Artifactory",
```

2022-12-01 18:40 UTC, susanev commented on pkg/codegen/docs/gen.go
> +		"awsx":					"AWSx (Pulumi Crosswalk for AWS)",
```suggestion
		"awsx":                             "AWSx (Pulumi Crosswalk for AWS)",
```

2022-12-01 18:40 UTC, susanev commented on pkg/codegen/docs/gen.go
> +		"command":				"Command (preview)",
```suggestion
		"command":                             "Command (preview)",
```

2022-12-01 18:40 UTC, susanev commented on pkg/codegen/docs/gen.go
> +		"ec":					"ElasticCloud (EC)",
```suggestion
		"ec":                             "ElasticCloud (EC)",
```

2022-12-01 18:41 UTC, susanev commented on pkg/codegen/docs/gen.go
> +		"artifactory":                             "Artifactory",
```suggestion
		"artifactory":                          "Artifactory",
```

2022-12-01 18:41 UTC, susanev commented on pkg/codegen/docs/gen.go
> +		"awsx":                             "AWSx (Pulumi Crosswalk for AWS)",
```suggestion
		"awsx":                                 "AWSx (Pulumi Crosswalk for AWS)",
```

2022-12-01 18:41 UTC, susanev commented on pkg/codegen/docs/gen.go
> +		"command":                             "Command (preview)",
```suggestion
		"command":                              "Command (preview)",
```

2022-12-01 18:41 UTC, susanev commented on pkg/codegen/docs/gen.go
> +		"ec":                             "ElasticCloud (EC)",
```suggestion
		"ec":                                   "ElasticCloud (EC)",
```

2022-12-03 06:00 UTC, justinvp requested changes

2022-12-03 13:22 UTC, susanev commented on pkg/codegen/docs/gen.go
> +
@justinvp I could use your help on Monday all of these came from what I thought was the right gen command to run, which was obviously wrong.

2022-12-03 13:43 UTC, susanev commented on pkg/codegen/docs/gen.go
> +
well nevermind, i started over and its clean, going to close this in favor of https://github.com/pulumi/pulumi/pull/11525

2022-12-03 13:43 UTC, closed without merging