Update dotnet codegen to net6.0
pulumi/pulumi pull request #12333
Opened 2023-03-02 16:36 UTC by Frassle

# Description

netcore3.1 is out of support, we've just been waiting on ecosystem and providers to update build scripts to support this.

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

2023-03-02 16:40 UTC, t0yv0 approved these changes
This LGTM. Just would be nice to get an ack from providers - 

@danielrbradley @kpitzen 

AFAIK all mainline providers are ready also except for this one bit:

https://github.com/pulumi/pulumi-aws/issues/2351

It should be a few minutes to get that in though.

2023-03-02 19:49 UTC, abhinav approved these changes

2023-03-02 21:31 UTC, kpitzen requested changes
Sticking this comment here to prevent merging before we (providers) have determined we're ready for 3.1 support to be dropped.  Already cc'd here, but cc anyway: @danielrbradley

2023-03-03 14:23 UTC, kpitzen approved these changes

2023-03-03 14:34 UTC, dixler commented
bors merge

2023-03-03 15:04 UTC, merged