[cli] Improve interactive scrolling
pulumi/pulumi pull request #12363
Opened 2023-03-06 15:38 UTC by pgavlin

These changes make two improvements to scrolling in the interactive display:

1. The interactive display can now be scrolled using the page-down and
   page-up keys. These keys scroll the display N lines at a time, where N is
   the height of the terminal.
2. If the display is scrolled to the bottom, it will now autoscroll it as new lines
   are added to the output.

2023-03-06 16:09 UTC, dixler requested changes
Hi. I'm in the process of working on https://github.com/pulumi/pulumi/issues/12320

I would like to block changes to this area while I'm figuring out how to resolve the p1.

2023-03-06 21:04 UTC, pgavlin commented
> Hi. I'm in the process of working on #12320
> 
> I would like to block changes to this area while I'm figuring out how to resolve the p1.

Ah, I wasn't aware we were tracking with a bug.

I believe that these changes help address that P1: they allow for faster scrolling and help ensure that newer resources appear on screen in a fashion similar to the earlier renderer.

2023-03-07 15:58 UTC, dixler commented
> > Hi. I'm in the process of working on #12320
> > I would like to block changes to this area while I'm figuring out how to resolve the p1.
> 
> Ah, I wasn't aware we were tracking with a bug.
> 
> I believe that these changes help address that P1: they allow for faster scrolling and help ensure that newer resources appear on screen in a fashion similar to the earlier renderer.

I'll take a look.

2023-03-07 16:30 UTC, dixler approved these changes
Thanks for the PR. I have a few nits, but looks fine as it's an overall improvement.

Scrolling doesn't view prior resources, but that's fine as we may rethink the overall UI experience.

2023-03-07 16:30 UTC, dixler commented on pkg/backend/display/internal/terminal/term.go
> +	if b >= 0x30 && b < 0x7f {
> would appreciate a comment explaining the significance of these values

here as well

2023-03-07 17:21 UTC, dixler commented
It looks like a test is failed. I'll rerun
```
=== FAIL: backend/display TestProgressEvents/template-body.jsoninteractive/80x24/raw (1.35s)
```

2023-03-07 20:47 UTC, pgavlin commented
bors merge

2023-03-07 21:21 UTC, merged