CONTRIBUTING: Clarify gofumpt further
pulumi/pulumi pull request #12860
Opened 2023-05-10 23:46 UTC by abhinav

We mention that you need to install gofumpt,
but it's easy to miss that there's some editor setup involved.

Also, gofumpt is not mentioned in the `brew install` which, depending on editor, may be necessary. (Editors that use gopls don't need to install it globally, but editors that invoke it manually need it installed.)

Ref: https://github.com/pulumi/pulumi/pull/12854#discussion_r1190467688

2023-05-10 23:57 UTC, guineveresaenger requested changes
Can we add instructions to "Submitting A Pull Request" as well? The workspace setup is useful if you're working on this repo every day, but a casual contributor may want to just run it manually.

2023-05-11 00:07 UTC, abhinav commented
Done!

2023-05-11 00:47 UTC, justinvp approved these changes

2023-05-11 00:52 UTC, guineveresaenger approved these changes

2023-05-11 14:55 UTC, RobbieMcKinstry commented
bors r+

2023-05-11 16:29 UTC, abhinav commented
bors retry

2023-05-11 17:17 UTC, merged