Dixler/12546/deprecated 2
pulumi/pulumi pull request #13890
Opened 2023-09-06 19:55 UTC by dixler

# Description

Removes Resource constructor deprecation checks in favor of deprecation checks in the ResourceArgs constructor.

Checks in the ResourceArgs constructor which will be changed to `ResourceArgs.__configure__` in #13825 and compatible with dicts and objects that implement `__getitem__` `__setitem__`.

Fixes #12546 

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [ ] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

2023-09-08 15:24 UTC, Frassle requested changes

2023-09-08 16:34 UTC, dixler commented on pkg/codegen/testing/test/testdata/regress-py-12546/schema.json
> -          "deprecationMessage": "Dear future maintainer, if there are changes here, make sure that this is printed before the value is set to the default or else this will always print.",
There are 3 more above it. I initially added it to add variety with a prior approach, but I'll revert this change as it's vestigial to this change.

2023-09-08 16:41 UTC, dixler commented on pkg/codegen/testing/test/testdata/regress-py-12546/schema.json
> -          "deprecationMessage": "Dear future maintainer, if there are changes here, make sure that this is printed before the value is set to the default or else this will always print.",
Addressed

2023-09-11 21:13 UTC, Frassle commented on pkg/codegen/testing/test/testdata/regress-py-12546/python-extras/tests/test_codegen.py
> +        """
```suggestion
```

No need for doc comments about the abstract method in test code.

2023-09-11 21:13 UTC, Frassle commented on pkg/codegen/testing/test/testdata/regress-py-12546/python-extras/tests/test_codegen.py
> +        pulumi_plant.tree.v1.RubberTree("my-tree", pulumi_plant.tree.v1.RubberTreeArgs())
Wasn't totally obvious what this was testing to start, I would add a doc comment to this method saying what we're doing "constructing a resource with deprecated but default values and checking the default values don't trigger a deprecation warning"

2023-09-12 06:24 UTC, Frassle approved these changes

2023-09-12 16:42 UTC, merged