[cli/import] Minimize logical name changes
pulumi/pulumi pull request #14705
Opened 2023-11-30 17:29 UTC by pgavlin

The trickiest job we do while parsing the import file is name disambiguation.

The name of an import serves as both the logical name of the imported resource (e.g. "foo" in `new aws.s3.Bucket("foo")`) and as the name of the resource's definition (e.g. `foo_1` in
`const foo_1 = new aws.s3.Bucket("foo")`). The logical name of the resource need only be unique within its qualified type--that is, two resources may have the same logical name if they are of different types or have different ancestors--but the name of the resource's definition must always be unique.

Other systems that serve as input for import (notably Terraform) also have this sort of peculiar type-based namespacing. We often see overlapping names when importing from these systems. In order to make `pulumi import` cooperate nicely with `pulumi convert`, we need the logical names of the imported resource to agree with the logical name of the corresponding converted resource.

To address this:
- We only change the logical name of a resource if not doing so would cause it to conflict with another resource (i.e. because they end up with the same URN)
- We change the definition name of a resource if not doing so would cause its definition in the generated source to conflict with another resource

# Description

Fixes # (issue)

## Checklist

- [ ] I have run `make tidy` to update any new dependencies
- [ ] I have run `make lint` to verify my code passes the lint check
  - [ ] I have formatted my code using `gofumpt`

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Cloud API version

2023-11-30 17:32 UTC, pgavlin commented
Not sure if we have an issue open for this one. This addresses disagreements in the logical resource names generated by `pulumi import --from terraform` and `pulumi convert --from terraform` for TF state/config with overlapping logical resource names.

2023-11-30 18:07 UTC, Frassle requested changes
I've got a change in-progress built on top of https://github.com/pulumi/pulumi/pull/14548 to fix this. Not raised a PR for that yet, but the issue for this is https://github.com/pulumi/pulumi/issues/14618.

It's not exactly the same as this approach, adding a new field to the import file instead to cover the cases where we need a unique name for parent reasons but don't want to change the logical name.

I was thinking of removing the auto-renaming support completely as part of that (because now it would only error if the full URN was a duplicate), but we could keep it as you've done here of auto-renaming.

2024-06-21 11:46 UTC, lunaris commented
Can we close this now that https://github.com/pulumi/pulumi/pull/14745 has landed? Based on the commentary here it seems like that's the approach we've decided to go with?

2024-06-24 14:21 UTC, lunaris commented
Speaking to @Frassle I think we _can_ close this as covered by the mentioned issue but feel free to reopen/discuss if not!

2024-06-24 14:21 UTC, closed without merging