Remove P characters from json schema regex
pulumi/pulumi pull request #18097
Opened 2024-12-20 23:30 UTC by Frassle

The "?P" capturing group is a Go specific regex feature (https://github.com/google/re2/wiki/Syntax), not part of ECMA 262 (javascript) which json schema is specified to use.

This removes the ?P syntax from the pulumi metaschema for better support with JSON schema libraries.

2024-12-23 07:56 UTC, tgummerer submitted a review, later dismissed
Looks reasonable to me, though we should look into why all the downstream tests are failing before merging this.

2024-12-23 11:09 UTC, Frassle commented
Yeh that's odd the downstream tests are failing with:
```
panic: jsonschema: jsonschema blob://pulumi.json compilation failed
[I#] [S#] doesn't validate with https://json-schema.org/draft/2020-12/schema#
  [I#] [S#/allOf/1] allOf failed
    [I#] [S#/allOf/1/$ref] doesn't validate with 'https://json-schema.org/draft/2020-12/meta/applicator#'
      [I#/properties/version] [S#/properties/properties/additionalProperties/$dynamicRef] doesn't validate with 'https://json-schema.org/draft/2020-12/schema#'
        [I#/properties/version] [S#/allOf/3] allOf failed
          [I#/properties/version] [S#/allOf/3/$ref] doesn't validate with 'https://json-schema.org/draft/2020-12/meta/validation#'
            [I#/properties/version/pattern] [S#/properties/pattern/format] '^v?(?<major>0|[1-9]\\d*)\\.(?<minor>0|[1-9]\\d*)\\.(?<patch>0|[1-9]\\d*)(?:-(?<prerelease>(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$' is not valid 'regex'

goroutine 1 [running]:
github.com/santhosh-tekuri/jsonschema/v5.(*Compiler).MustCompile(0x0?, {0x1e9[80](https://github.com/pulumi/pulumi-gcp/actions/runs/12440103585/job/34735376377#step:16:81)d9?, 0x0?})
	/home/runner/go/pkg/mod/github.com/santhosh-tekuri/jsonschema/v5@v5.0.0/compiler.go:97 +0x6b
github.com/pulumi/pulumi/pkg/v3/codegen/schema.init.0()
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.143.1-0.20241220232238-ddd6aa053b91/codegen/schema/bind.go:53 +0x93
```

But this same init code is running fine in the tests in this repo.

2024-12-23 13:47 UTC, Frassle commented
Ah found it.

https://github.com/golang/go/issues/64108#issuecomment-1810005219

The non-P form is only supported from 1.22 onwards. Technically given that 1.23 was released in August we only support 1.22 and higher.

I'll nudge providers that they need to update, but hold off merging this for a while for their benefit.

2024-12-23 14:19 UTC, Frassle commented
Another alternative approach if we wanted to make this ECMA compliant (I do) but not break Go 1.21 is to just remove all the named groupings. There not used as part of schema validation.

2024-12-23 17:10 UTC, blampe requested changes
`pkg/go.mod` should be bumped if we're requiring 1.22 semantics -- it's currently still 1.21.

Ref https://go.dev/ref/mod#go-mod-file-go

2025-02-06 10:42 UTC, Frassle commented
Reverted this back to just removing the P characters. The go.mod was updated to 1.22 in https://github.com/pulumi/pulumi/pull/18274.

2025-02-06 10:47 UTC, tgummerer approved these changes

2025-02-06 12:08 UTC, merged