Remove author name and committer name. Fixes #5430
pulumi/pulumi pull request #5567
Opened 2020-10-14 16:12 UTC by cvhariharan

This PR fixes #5430 where the author and committer names were being sent from the CLI.

2020-11-11 16:48 UTC, chrsmith requested changes
Sorry for not coming across this sooner. I'll leave some more detailed notes on the root issue, but we should keep the author/committer names in the update metadata.

While it is true the author information could be derived from the commit hash, that also means that the Pulumi backend would need to be given access to the repo too. And that, IMHO, seems like the wrong tradeoff. Since the backend -- whether it is app.pulumi.com, or some other implementation -- would benefit from being able to say _who_ committed the code. (But does not need to know the contents of the code itself.)

So rather than just removing the metadata values entirely (since they are useful), it might be more prudent to simply allow an opt-out. For example, omitting all of the `GitCommiter` and `GitAuthor` metadata values if `PULUMI_OMIT_COMMIT_AUTHOR_METADATA` is truthy.

2020-12-15 19:00 UTC, leezen commented
@cvhariharan Any chance you've had time to take a look?

2020-12-16 17:03 UTC, cvhariharan commented
@leezen Sorry, I have been caught up with work and haven't been able to look into this. I'll try to look into this over the weekend and give an update.

2021-02-25 23:21 UTC, leezen commented
@cvhariharan Just checking in to see if you're planning to respond to the PR feedback?

2021-02-26 14:28 UTC, cvhariharan commented
Hi @leezen, I am not able to find time to look into this. Kindly assign this to someone else. Sorry, I forgot inform earlier.

2021-02-27 00:39 UTC, leezen commented
Thanks for the update. I'll close this PR for now.

2021-02-27 00:39 UTC, closed without merging