[FIX] unprotect cmd example
pulumi/pulumi pull request #8430
Opened 2021-11-16 15:52 UTC by raphaelauv

when I run `pulumi up` with a protected resource pulumi give an example , but that example is not working

```
    error: Preview failed: unable to delete resource "urn:pulumi:XXXXXX::XXXX::gcp:component:all_resource$gcp:storage/bucket:Bucket::bucket_XXXXX"
    as it is currently marked for protection. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumiprogram and run `pulumi up` or use the command:
    `pulumi state unprotect urn:pulumi:XXXX::XXXX::gcp:component:all_resource$gcp:storage/bucket:Bucket::bucket_XXXXXX`
```

If I run the example cmd , it throw : 

```log
error: No such resource "urn:pulumi:XXXX::XXX::gcp:component:all_resource:storage/bucket:Bucket::bucket_XXXXX" exists in the current state
```

If i put around the urn some ```  it work  : 

```
`pulumi state unprotect `urn:pulumi:XXXX::XXXX::gcp:component:all_resource$gcp:storage/bucket:Bucket::bucket_XXXXXX`
```

# Description

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

2021-11-17 00:18 UTC, svangordon-fruit commented
If I had to guess, this is related to escaping of special characters in the URN (especially `$`). IIRC, in the docs it's recommended to surround URNs in single quotes (`'`) to avoid variable interpolation. Single quotes might be more portable across shells than backticks.

2021-11-17 22:56 UTC, iwahbe requested changes

2021-11-17 22:56 UTC, iwahbe commented on pkg/resource/deploy/step.go
> +			"`pulumi state unprotect `%s``", s.old.URN, s.old.URN)
```suggestion
			"`pulumi state unprotect '%s'`", s.old.URN, s.old.URN)
```
I agree with @svangordon-fruit. We should use `'`. Backtick doesn't work on bash or zsh or fish, off the top of my head.

2021-11-19 18:51 UTC, iwahbe commented
/run-acceptance-tests

2021-11-19 20:38 UTC, iwahbe approved these changes
LGTM

2021-11-19 20:39 UTC, merged