Don't type test for stack tags in pulumi new
pulumi/pulumi pull request #9113
Opened 2022-03-04 12:52 UTC by Frassle

Move Tags to just be on Stack. Saves a type test in `pulumi new`.

Given Tags doesn't actually do a fetch the only error you can really get back from it is that the backed doesn't support tags.

2022-03-22 10:50 UTC, Zaid-Ajaj approved these changes

2022-03-22 17:43 UTC, iwahbe requested changes

2022-03-22 17:43 UTC, iwahbe commented on pkg/cmd/pulumi/new.go
> +		tags, err := s.Tags()
Could we check for that error and propagate all others. If a new error is added, or something unexpected happens, I don't want to silently eat errors. 

If the only possible error for `Tags` is "not supported", maybe change the return type from `error` to a bool indicating if tags are supported.

2022-03-23 16:03 UTC, iwahbe approved these changes

2022-03-23 22:05 UTC, merged