Add --insecure option to `pulumi login`
pulumi/pulumi pull request #9159
Opened 2022-03-09 17:37 UTC by Frassle

# Description

Add --insecure option to `pulumi login` which disables https certificate checks.

Fixes https://github.com/pulumi/pulumi/issues/9120

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

2023-02-03 18:39 UTC, lukehoban approved these changes
Is there any reasonable way to add test coverage for this?

2023-02-03 23:17 UTC, justinvp requested changes
I was thinking of force pushing a squashed commit to your branch that addresses my suggestions (fixes the bug, and removes the `-k` shorthand), and adds a changelog, to get it merged today. We can follow-up on adding test coverage.

2023-02-03 23:17 UTC, justinvp commented on pkg/cmd/pulumi/login.go
> +	cmd.PersistentFlags().BoolVarP(&localMode, "insecure", "k", false, "Allow insecure server connections when using SSL")
```suggestion
	cmd.PersistentFlags().BoolVarP(&insecure, "insecure", "k", false, "Allow insecure server connections when using SSL")
```

2023-02-03 23:17 UTC, justinvp commented on pkg/cmd/pulumi/login.go
> +	cmd.PersistentFlags().BoolVarP(&localMode, "insecure", "k", false, "Allow insecure server connections when using SSL")
Also, why `-k` for the shorthand char? Do we even need a shorthand for this one?

2023-02-04 00:12 UTC, justinvp approved these changes
I force pushed a squashed commit w/ feedback addressed.

2023-02-04 02:53 UTC, justinvp commented
bors merge

2023-02-04 04:41 UTC, merged