Return errors on parse failures for `config.Try*`
pulumi/pulumi pull request #9407
Opened 2022-04-15 12:08 UTC by iwahbe

# Description

`config.Try*` returns an error message if a config key is missing, but there is currently no way to guarantee that a key is pulled from the config. When a non-string primitive key is tried, a failure to parse leads returns the type appropriate zero value. This is super counterintuitive to me. Especially since `config.TryObject` does return a parse error when appropriate. 

This is a breaking change, but it is hard to imagine a situation where `config.Try*` is used correctly. Therefore I believe the change is appropriate. 

This PR changes the behavior of `config.Try*` to return an error if either the requested key is missing in the config or if the key is invalid for the requested type. 

## Example:
```go
cfg := config.New(ctx, "dev")
v, err := cfg.TryInt("key")
if errors.Is(err, config.ErrMissingVar) {
    // Set a default
    v = 42
} else {
    // We set the value incorrectly
    panic(fmt.Errorf(`Attempted to pass default value "%s" as float64: %w`, cfg.Require("key"), err))
}
```

## Checklist

- [X] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

2022-04-15 16:17 UTC, pgavlin requested changes
CHANGELOG_PENDING needs to be cleaned up; LGTM otherwise.

2022-04-15 16:17 UTC, pgavlin commented on CHANGELOG_PENDING.md
> +<<<<<<< HEAD
This file needs a merge

2022-04-15 16:17 UTC, pgavlin commented on sdk/go/pulumi/config/require.go
> +		contract.Failf("unable to parse required configuration variable '%s'; %s", key, err.Error())
Huh, weird that we use `contract.Fail` in the config APIs. Might consider just changing these to raw `panic`s.

2022-04-18 19:39 UTC, pgavlin commented on sdk/go/pulumi/config/require.go
> +	panic(fmt.Sprintf(format, a...))
Nit: I'd panic with an error here to make it a bit easier to recover if necessary.

```suggestion
	panic(fmt.Errorf(format, a...))
```

2022-04-18 19:39 UTC, pgavlin approved these changes

2022-04-19 15:39 UTC, iwahbe commented on pkg/codegen/pcl/rewrite_convert.go
> +// lowerConversion performs the main logic of LowerConversion. nil, false is
Yes it did. Changed to a new branch https://github.com/pulumi/pulumi/pull/9426. I'll revert it here.

2022-04-20 07:46 UTC, merged