Pin and enable caching installed tools
pulumi/pulumi pull request #9628
Opened 2022-05-19 20:25 UTC by t0yv0

# Description

Uses the new facility in jaxxstorm/action-install-gh-release to cache the tools (has to pin them to cache). Aimed at avoiding ratelimit issues.

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

2022-05-19 20:26 UTC, dixler approved these changes
LGTM

2022-05-19 20:27 UTC, dixler requested changes
Error: Unable to reserve cache with key action-install-gh-release/pulumi/pulumictl/v0.0.31/linux-x64, another job may be creating this cache. More details: Cache already exists. Scope: refs/pull/9628/merge, Key: action-install-gh-release/pulumi/pulumictl/v0.0.31/linux-x64, Version: b7e495078f01e0ba3aac532b3e4b5eb2809dcb6b5752b5d432363c38c69bce7a

2022-05-19 20:28 UTC, t0yv0 commented
Yes, not good. We might need to add some defensive logic to avoid failing on this. 

That being said, I think I can just restart the build after everything-but-one errors out, and it might just work.  Let's see.

2022-05-19 20:30 UTC, t0yv0 commented
Like some steps hit the cache OK:

https://github.com/pulumi/pulumi/runs/6514497835?check_suite_focus=true#step:6:21

2022-05-19 20:50 UTC, t0yv0 commented
Related bugfix: https://github.com/jaxxstorm/action-install-gh-release/pull/24

2022-05-20 15:18 UTC, dixler approved these changes
LGTM azure downstream failed, but trusting your discretion.

2022-05-20 15:35 UTC, t0yv0 commented
It failed on ```[Test azure-native Downstream](https://github.com/pulumi/pulumi/runs/6525814963?check_suite_focus=true#step:8:58217)
API rate limit exceeded for installation ID 807028.```

Seems like an unrelated flake to me.

2022-05-20 15:36 UTC, merged