Clone and test pulumi/templates from the current working branch
pulumi/pulumi pull request #9804
Opened 2022-06-08 10:22 UTC by Zaid-Ajaj

# Description

Right now, when we are raising a PR in pulumi/templates, it uses [workspace.RetrieveTemplates](https://github.com/pulumi/templates/blob/master/tests/template_test.go#L70) which in turn calls [retrievePulumiTemplates](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/workspace/templates.go#L311) in pulumi/pulumi that clones and tests the templates from `master` branch of pulumi/templates instead of cloning and testing the template changes from the raised PR 

> see [pulumi/templates#294](https://github.com/pulumi/templates/pull/294) where the problem comes to light: github actions building outdated templates from master branch and not the new ones

This PR makes sure that if we are running the tests of pulumi/templates that we are also cloning the right branch, not always defaulting to `master`

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

2022-06-08 16:57 UTC, iwahbe requested changes
Won't this pull in both the current branch and the default branch (since the `if !offline && currentGithubRepo == ...` block won't return without an error. Is that the intention? Otherwise, could we simplify by embedding something like the following in the `if !offline {` block:
```go
if b := os.Getenv("GITHUB_BRANCH"); os.Getenv("GITHUB_REPOSITORY") == "pulumi/templates" && b != "" {
    pulumiTemplatesBranch = b
}
```

2022-06-08 22:04 UTC, Zaid-Ajaj commented
@iwahbe nice catch! I've simplified it now

2022-06-09 09:08 UTC, Frassle approved these changes

2022-06-09 09:08 UTC, Frassle commented on sdk/go/common/workspace/templates.go
> +
```suggestion

```

2022-06-09 10:14 UTC, Zaid-Ajaj commented on sdk/go/common/workspace/templates.go
> +
Done!

2022-06-09 20:34 UTC, iwahbe approved these changes

2022-06-09 20:35 UTC, merged